# Generated by Django 4.1.4 on 2022-12-19 07:46

import ckeditor.fields
import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(choices=[('Toshkent', 'Toshkent'), ("Farg'ona", "Farg'ona"), ('Andijon', 'Andijon'), ('Namangan', 'Namangan'), ('Surxondaryo', 'Surxondaryo'), ('Qashqadaryo', 'Qashqadaryo'), ('Xorazm', 'Xorazm'), ('Navoiy', 'Navoiy'), ("Qoraqalpog'iston Resublikasi", "Qoraqalpog'iston Respublikasi"), ('Buxoro', 'Buxoro'), ('Toshkent shahri', 'Toshkent shahri'), ('Samarqand', 'Samarqand')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'City',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Yo'nalish nomi")),
                ('preview_photo', cloudinary.models.CloudinaryField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': "Yo'nalish",
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=70, verbose_name='Familiyasi')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(max_length=400, verbose_name='Doktor haqida ma`lumot')),
                ('preview_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('work_start_time', models.TimeField(verbose_name='Ishni boshlashnish vaqti')),
                ('work_end_time', models.TimeField(verbose_name='Ishni tugash vaqti')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.department', verbose_name="Doktor yo'nalishini tanlang:")),
            ],
            options={
                'verbose_name_plural': 'Doktor',
            },
        ),
        migrations.CreateModel(
            name='SickAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SicknessList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Kasallik nomi')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('about_sickness', models.TextField(blank=True, verbose_name='Kasallik haqida ta`rif')),
                ('untying', models.TextField(help_text='Ushbu kasallik yuz berganda qanday harakatlarni qilish haqida ta`rif')),
                ('over_18', models.CharField(max_length=50, verbose_name='18yoshdan yuqori insonlar uchun dori nomi va uning dozasi')),
                ('under_18', models.CharField(max_length=50, verbose_name='18yoshdan past bolalar uchun dori nomi va uning dozasi')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sickness List',
            },
        ),
        migrations.CreateModel(
            name='SickItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
            ],
            options={
                'verbose_name_plural': 'Kasallar',
                'ordering': ['order', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('address', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.city')),
            ],
            options={
                'verbose_name_plural': 'Hospital',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital', verbose_name='Kasalxonani tanlang:'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='sick_list',
            field=models.ManyToManyField(blank=True, through='hospital.SickItem', to=settings.AUTH_USER_MODEL),
        ),
    ]
