# Generated by Django 4.1.4 on 2022-12-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_doctor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
